/**
 * Node 4 — Asset Prompt Engineer (Gemini CLI 호출)
 *
 * 목적: Node 3 plan + references_catalog.json → ComfyUI(FLUX) 프롬프트 산출.
 *      5계층 카테고리 검색(W-1, W-3) + 임베딩 검색(BN-5) + 캐시 재사용 결정.
 *
 * v4.5 신규:
 *   - 5계층 검색 우선순위 (characters → static_assets → auto_generated_assets → props → 신규)
 *   - description_search(임베딩 인풋, 화풍 토큰 제거) / description_render(ComfyUI 인풋, 화풍 앵커 포함) 분리
 *   - 글로벌 화풍 앵커 코드 강제 suffix 주입
 *   - hnswlib 코사인 검색 (처음부터 도입, sentence-transformers/all-MiniLM-L6-v2 384차원)
 *   - reuse_asset_id 매칭 시 L1 캐시 합류 → ComfyUI 호출 스킵
 *   - search_log 출력 강제 (5계층 시도 결과 명시 기록)
 *
 * v5.0 멀티 포맷 Multi-Sourcing 지원:
 *   - character_style: "silhouette" → 프롬프트에 실루엣 강제어 주입
 *   - bg_style: "b_roll_video" → ComfyUI 스킵, Pexels API 분기 메타 부여 (source_api: "pexels")
 *   - bg_style: "real_photo" → ComfyUI 스킵, Pixabay API 분기 메타 부여 (source_api: "pixabay")
 *   - bg_style: "solid_color" → 배경 에셋 생성 전면 스킵 (GPU 절약)
 *   - bg_style: "illustration" → 기존 ComfyUI 파이프라인 유지
 *
 * 시드 정책 (EF-1):
 *   - 캐릭터/소품: SHA1(video_id + ref_image_id)의 32-bit 해시 (영상 1편 내 동일 시드)
 *   - 배경/전경: 씬 단위 시드 (scene_id 기반)
 *
 * 입력 (n8n items[].json):
 *   - chapter_id: string
 *   - plan_path: string
 *   - catalog_path: string (shared_assets/references_catalog.json)
 *
 * 워크플로우 전역:
 *   - $('Load Files').first().json.video_id
 *   - $('Load Files').first().json.project_root
 *
 * 출력 (씬별 1 아이템):
 *   - { chapter_id, scene_id, asset_prompts: [...], search_log: [...] }
 *   - asset_prompts 배열은 Node 5에서 split 후 Node 6 Switch로 분기.
 *
 * 환경: gemini CLI + python(임베딩) 시스템 PATH 가용.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { spawnSync } = require("child_process");

// ──────────────────────────────────────────────
// 공용 임베딩 검색 레이어 (과제 11)
// ──────────────────────────────────────────────

const embeddingSearch = require("./embedding_search.js");
const { embedTexts, cosine } = embeddingSearch;

// ──────────────────────────────────────────────
// 5계층 카테고리 검색
// ──────────────────────────────────────────────

const MATCH_SCORE_THRESHOLD = 0.7;
const EMBEDDING_THRESHOLD = embeddingSearch.constants.EMBEDDING_THRESHOLD;

function searchCatalog(catalog, query, opts = {}) {
  // query: { type, scene_pose_desc, scene_context, target_object_desc, tags, description_search }
  // opts:  { indexPath } — 과제 11 hnswlib 인덱스 경로 (있으면 그래프 탐색, 없으면 직접 코사인 폴백)
  const log = [];

  // tier 1: characters
  if (query.type === "character") {
    for (const [key, c] of Object.entries(catalog.characters || {})) {
      if (key.startsWith("_")) continue;
      const score = scoreCharacterMatch(c, query);
      log.push({ category: "characters", asset_id: key, score });
      if (score >= MATCH_SCORE_THRESHOLD) {
        return { hit: { tier: 1, category: "characters", asset_id: key, entry: c, score }, log };
      }
    }
  }

  // tier 2: static_assets (정확 ID 매칭만 — 임베딩 X)
  if (query.exact_static_id) {
    const sa = (catalog.static_assets || {})[query.exact_static_id];
    if (sa) {
      log.push({ category: "static_assets", asset_id: query.exact_static_id, score: 1.0 });
      return {
        hit: {
          tier: 2,
          category: "static_assets",
          asset_id: query.exact_static_id,
          entry: sa,
          score: 1.0,
        },
        log,
      };
    }
    log.push({ category: "static_assets", asset_id: query.exact_static_id, score: 0 });
  }

  // tier 3: auto_generated_assets — 과제 11 공용 레이어 위임 (hnswlib + 태그 폴백)
  if (query.description_search) {
    const r = embeddingSearch.searchAutoGenerated({
      catalog,
      indexPath: opts.indexPath,
      query: { description_search: query.description_search, tags: query.tags || [] },
      embedFn: opts.embedFn || embedTexts,
    });
    if (r.hit) {
      log.push({
        category: "auto_generated_assets",
        asset_id: r.hit.asset_id,
        score: r.hit.score,
        source: r.hit.source,
      });
      return {
        hit: {
          tier: 3,
          category: "auto_generated_assets",
          asset_id: r.hit.asset_id,
          entry: r.hit.entry,
          score: r.hit.score,
          source: r.hit.source,
        },
        log,
      };
    }
    if (r.log) {
      log.push({
        category: "auto_generated_assets",
        asset_id: null,
        score: r.log.top_sim || 0,
        reason: r.log.reason || "no_match",
      });
    }
  }

  // tier 4: props (img2img, match_score 기반)
  if (query.type === "prop") {
    for (const [key, p] of Object.entries(catalog.props || {})) {
      if (key.startsWith("_")) continue;
      const score = scorePropMatch(p, query);
      log.push({ category: "props", asset_id: key, score });
      if (score >= MATCH_SCORE_THRESHOLD) {
        return { hit: { tier: 4, category: "props", asset_id: key, entry: p, score }, log };
      }
    }
  }

  // tier 5: generate_asset:true 폴백
  log.push({ category: "generate_new", asset_id: null, score: 0 });
  return { hit: null, log };
}

function scoreCharacterMatch(c, query) {
  if (!query.scene_pose_desc) return 0;
  // 단순 키워드/태그 일치 비율
  const haystack = (c.appearance_anchor + " " + (c.tags || []).join(" ")).toLowerCase();
  const needles = (query.scene_pose_desc + " " + (query.scene_context || ""))
    .toLowerCase()
    .split(/\s+/);
  let hit = 0;
  for (const n of needles) if (n.length > 2 && haystack.includes(n)) hit++;
  return Math.min(1.0, hit / Math.max(3, needles.length / 2));
}

function scorePropMatch(p, query) {
  if (!query.target_object_desc) return 0;
  const haystack = (p.description + " " + (p.tags || []).join(" ")).toLowerCase();
  const needles = query.target_object_desc.toLowerCase().split(/\s+/);
  let hit = 0;
  for (const n of needles) if (n.length > 2 && haystack.includes(n)) hit++;
  return Math.min(1.0, hit / Math.max(2, needles.length / 2));
}

// ──────────────────────────────────────────────
// 시드 정책 (EF-1)
// ──────────────────────────────────────────────

function sha1Hex(s) {
  return crypto.createHash("sha1").update(s).digest("hex");
}

function seedForAsset(assetType, videoId, refImageId, sceneId) {
  if (assetType === "character" || assetType === "prop") {
    const h = sha1Hex(`${videoId}|${refImageId}`);
    return parseInt(h.slice(0, 8), 16) >>> 0;
  } else {
    // background / foreground: 씬 단위 시드
    const h = sha1Hex(`${videoId}|${sceneId}|${assetType}`);
    return parseInt(h.slice(0, 8), 16) >>> 0;
  }
}

// ──────────────────────────────────────────────
// 글로벌 화풍 앵커 강제 suffix
// ──────────────────────────────────────────────

function applyGlobalStyleAnchor(promptBody, catalog) {
  const anchor = catalog.global_style_anchor && catalog.global_style_anchor.anchor_text;
  if (!anchor) return promptBody;
  if (promptBody.toLowerCase().includes(anchor.toLowerCase())) return promptBody;
  return `${promptBody.trim()}, ${anchor}`;
}

// ──────────────────────────────────────────────
// 프롬프트 빌더 (Gemini CLI에 전달)
// ──────────────────────────────────────────────

const SYSTEM_DIRECTIVE = `당신은 정보성 모션 코믹 영상의 에셋 프롬프트 엔지니어입니다.
Node 3의 연출 기획안을 받아 ComfyUI(FLUX)에 보낼 영문 프롬프트를 씬별로 추출합니다.
출력은 반드시 지정된 JSON 스키마만 따릅니다.`;

const ASSET_TYPE_RULE = `[asset_type 강제 태깅]
각 프롬프트 객체는 반드시 asset_type을 "character" / "prop" / "background" / "foreground" 중 하나로 지정.
- character: 인물. isolated single object, centered, perfect composition for transparent PNG 지시어 강제.
- prop: 소품. 동일 transparent PNG 지시어 강제.
- background: 16:9 풀씬 배경. transparent 지시어 절대 금지.
- foreground: 카메라 앞 오브젝트(난간, 창, 나뭇가지 등). transparent 지시어 강제 + zoom_rate 1.25 메타 부여.`;

const DESCRIPTION_SPLIT_RULE = `[description_search vs description_render 분리]
- description_search: 화풍 토큰 제거된 핵심 명사구 (임베딩 검색 인풋).
  예: "korean male anchor 40s navy suit glasses authoritative"
- description_render: 풀 영문 프롬프트 (ComfyUI 호출 인풋). 글로벌 화풍 앵커가 코드로 자동 suffix 주입됨.
  예: "A 40-something Korean male anchor, wearing a navy suit..."
- tags: 영문 태그 배열 (Node 9.5 자동 등재 시 사용).`;

const SEARCH_PRIORITY_RULE = `[5계층 검색 우선순위 — match_score 기록 강제]
1. characters (FaceID 강제, match_score >= 0.7)
2. static_assets (정확 ID 매칭, 임베딩 X)
3. auto_generated_assets (코사인 유사도 >= 0.85, hnswlib)
4. props (img2img, match_score >= 0.7)
5. generate_asset:true 폴백 (신규 ComfyUI 호출, Node 9.5가 자동 등재)
- 각 시도의 결과(category, asset_id, score)를 search_log 배열에 명시 기록 필수.
- match_score < 0.7이면 다음 순위 자동 폴백.`;

const POSE_RULE = `[pose 분기 (Node 3 출력 그대로 반영)]
- pose:"auto" → IP-Adapter 0.65 + FaceID 0.85, ControlNet 미적용 (FLUX 창의 구도)
- pose:"<id>" → IP-Adapter 0.30~0.40 + FaceID 0.85 + ControlNet OpenPose
- character_pose 자연어 묘사는 pose:auto일 때 단독 영향, pose:<id>일 때 보조 묘사로 프롬프트에 포함.`;

const REGION_RULE = `[region_id 필드 강제 (MO-5)]
모든 자산 출력에 region_id 필드 강제.
- layout이 없는 일반 씬: region_id:"default"
- layout 활성 씬: layout.regions[].region_id 중 하나 (left/right/top 등)
- region_id는 Node 9가 폴더 구조 산출 시 그대로 키로 사용.`;

const OUTPUT_SCHEMA = `[출력 JSON 스키마 — 정확히 이 형태로만]
{
  "chapter_id": "<입력값>",
  "scenes": [
    {
      "scene_id": "scene_NN",
      "asset_prompts": [
        {
          "asset_type": "character" | "prop" | "background" | "foreground",
          "scene_asset_id": "character_01" | "prop_01" | "background" | "foreground",
          "region_id": "default" | "<layout.regions[].region_id>",
          "description_search": "<화풍 토큰 제거 명사구>",
          "description_render": "<풀 영문 프롬프트, 화풍 앵커 코드로 자동 suffix>",
          "tags": ["english","tags","array"],
          "ref_image_id_query": "<카탈로그 검색용 — 'none' 또는 후보 ID>",
          "exact_static_id": "<static_<key> — 정확 ID 매칭 시도>",
          "pose": "auto" | "pose_<id>",
          "position": "left" | "center" | "right"
        }
      ]
    }
  ]
}
- 본 코드(Node 4 JS)가 카탈로그 검색을 실행하여 reuse_asset_id / generate_asset / seed / search_log를 자동 부여.
- LLM 출력에는 reuse_asset_id, seed, search_log 필드를 넣지 말 것 (코드가 책임).`;

function buildPrompt(plan, catalog) {
  return [
    SYSTEM_DIRECTIVE,
    "",
    `[입력 plan]\n${JSON.stringify(plan, null, 2)}\n`,
    `[참조 카탈로그 요약]\n` +
      `characters: ${Object.keys(catalog.characters || {})
        .filter((k) => !k.startsWith("_"))
        .join(", ")}\n` +
      `props: ${Object.keys(catalog.props || {})
        .filter((k) => !k.startsWith("_"))
        .join(", ")}\n` +
      `static_assets: ${Object.keys(catalog.static_assets || {})
        .filter((k) => !k.startsWith("_"))
        .join(", ")}\n` +
      `(auto_generated_assets는 코드가 임베딩 검색)\n` +
      `global_style_anchor: ${catalog.global_style_anchor?.anchor_text || ""}\n`,
    "",
    ASSET_TYPE_RULE,
    "",
    DESCRIPTION_SPLIT_RULE,
    "",
    SEARCH_PRIORITY_RULE,
    "",
    POSE_RULE,
    "",
    REGION_RULE,
    "",
    OUTPUT_SCHEMA,
  ].join("\n");
}

// ──────────────────────────────────────────────
// Gemini CLI 호출
// ──────────────────────────────────────────────

function callGeminiCli(prompt, retries = 3) {
  for (let attempt = 1; attempt <= retries; attempt++) {
    const result = spawnSync("gemini", ["--prompt", prompt, "--format", "json"], {
      encoding: "utf-8",
      maxBuffer: 50 * 1024 * 1024,
      timeout: 180000,
    });
    if (result.status === 0 && result.stdout) {
      try {
        return JSON.parse(
          result.stdout
            .trim()
            .replace(/^```json\s*/, "")
            .replace(/```$/, "")
        );
      } catch (e) {
        if (attempt === retries) throw new Error(`[Node 4] JSON 파싱 실패: ${e.message}`);
      }
    } else if (attempt === retries) {
      throw new Error(`[Node 4] Gemini CLI 실패: ${result.stderr || "unknown"}`);
    }
  }
}

// ──────────────────────────────────────────────
// 후처리: 카탈로그 검색 + 시드 부여 + 화풍 앵커 + reuse_asset_id 결정
// ──────────────────────────────────────────────

function postProcessAssets(geminiOutput, catalog, videoId, opts = {}) {
  const enriched = [];
  for (const sc of geminiOutput.scenes || []) {
    // V5.0: 씬 레벨 포맷 속성 추출 (Node 3 출력)
    const sceneData = {
      bg_style: sc.bg_style || "illustration",
      character_style: sc.character_style || "webtoon",
      foreground_style: sc.foreground_style || "none",
      overlay_focus: sc.overlay_focus || "none",
      search_query: sc.search_query || null,
    };

    // V5.0: bg_style가 "solid_color"이면 배경 에셋 생성 스킵 (GPU 절약)
    const skipBgGeneration = sceneData.bg_style === "solid_color";
    // V5.0: bg_style가 "b_roll_video" 또는 "real_photo"이면 ComfyUI 대신 API 라우팅
    const apiSourceBg = sceneData.bg_style === "b_roll_video" ? "pexels"
                      : sceneData.bg_style === "real_photo" ? "pixabay"
                      : null;

    for (const ap of sc.asset_prompts || []) {
      // V5.0: 배경 에셋에 대한 분기 처리
      if (ap.asset_type === "background") {
        if (skipBgGeneration) {
          // solid_color → 에셋 생성 전면 스킵, CSS만으로 처리
          enriched.push({
            chapter_id: geminiOutput.chapter_id,
            scene_id: sc.scene_id,
            asset_type: "background",
            scene_asset_id: ap.scene_asset_id || "background",
            region_id: ap.region_id || "default",
            skip_comfyui: true,
            source_api: null,
            bg_style: "solid_color",
            character_style: sceneData.character_style,
            foreground_style: sceneData.foreground_style,
            overlay_focus: sceneData.overlay_focus,
            search_query: null,
            search_log: [{ category: "solid_color_skip", asset_id: null, score: 0 }],
          });
          continue;
        }
        if (apiSourceBg) {
          // b_roll_video → Pexels API / real_photo → Pixabay API
          enriched.push({
            chapter_id: geminiOutput.chapter_id,
            scene_id: sc.scene_id,
            asset_type: "background",
            scene_asset_id: ap.scene_asset_id || "background",
            region_id: ap.region_id || "default",
            skip_comfyui: true,
            source_api: apiSourceBg,
            bg_style: sceneData.bg_style,
            character_style: sceneData.character_style,
            foreground_style: sceneData.foreground_style,
            overlay_focus: sceneData.overlay_focus,
            search_query: sceneData.search_query,
            search_log: [{ category: `api_${apiSourceBg}`, asset_id: null, score: 0 }],
          });
          continue;
        }
      }
      // 카탈로그 검색 (과제 11: tier-3은 indexPath로 hnswlib 그래프 탐색)
      const searchQuery = {
        type: ap.asset_type,
        scene_pose_desc: ap.description_search,
        scene_context: ap.description_render,
        target_object_desc: ap.description_search,
        description_search: ap.description_search,
        tags: ap.tags || [],
        exact_static_id: ap.exact_static_id,
      };
      const { hit, log } = searchCatalog(catalog, searchQuery, { indexPath: opts.indexPath });

      // reuse_asset_id 결정
      let reuse_asset_id = null;
      let generate_asset = false;
      let ref_image_id = "none";
      if (hit) {
        if (hit.tier === 1 || hit.tier === 4) {
          // characters / props → ref_image_id 사용 (FaceID/img2img 강제)
          ref_image_id = hit.entry.variants
            ? Object.values(hit.entry.variants)[0].ref_image_id
            : hit.entry.ref_image_id;
        } else {
          // static / auto_generated → reuse_asset_id (ComfyUI 스킵, L1 합류)
          reuse_asset_id = hit.asset_id;
        }
      } else {
        generate_asset = true;
      }

      // 글로벌 화풍 앵커 코드 강제 suffix
      let renderPrompt = applyGlobalStyleAnchor(ap.description_render, catalog);

      // ── V5.0: character_style "silhouette" → 프롬프트 강제 변환 ──
      if (sceneData.character_style === "silhouette" && ap.asset_type === "character") {
        renderPrompt = `pure black solid silhouette, flat vector shape, white background, ${renderPrompt}`;
      }

      // 시드 결정
      const seed = seedForAsset(ap.asset_type, videoId, ref_image_id, sc.scene_id);

      enriched.push({
        chapter_id: geminiOutput.chapter_id,
        scene_id: sc.scene_id,
        asset_type: ap.asset_type,
        scene_asset_id: ap.scene_asset_id,
        region_id: ap.region_id || "default",
        description_search: ap.description_search,
        description_render: renderPrompt,
        tags: ap.tags || [],
        pose: ap.pose || "auto",
        position: ap.position || "center",
        ref_image_id,
        reuse_asset_id,
        generate_asset,
        seed,
        lora_signature: catalog.global_style_anchor
          ? `noir_webtoon_style@${catalog.global_style_anchor.version}`
          : "noir_webtoon_style",
        search_log: log,
        // ── V5.0 멀티 포맷 메타 (Node 6/7 라우팅용) ──
        bg_style: sceneData.bg_style || "illustration",
        character_style: sceneData.character_style || "webtoon",
        foreground_style: sceneData.foreground_style || "none",
        overlay_focus: sceneData.overlay_focus || "none",
        search_query: sceneData.search_query || null,
      });
    }
  }
  return enriched;
}

// ──────────────────────────────────────────────
// 출력 검증
// ──────────────────────────────────────────────

function validateAssets(assets) {
  const errors = [];
  for (let i = 0; i < assets.length; i++) {
    const a = assets[i];
    const tag = `assets[${i}]`;
    if (!["character", "prop", "background", "foreground"].includes(a.asset_type))
      errors.push(`${tag}.asset_type 형식 오류: ${a.asset_type}`);
    if (!a.scene_asset_id) errors.push(`${tag}.scene_asset_id 누락`);
    if (!a.region_id) errors.push(`${tag}.region_id 누락 (MO-5)`);
    if (!a.description_search) errors.push(`${tag}.description_search 누락 (임베딩 인풋)`);
    if (!a.description_render) errors.push(`${tag}.description_render 누락 (ComfyUI 인풋)`);
    if (!Array.isArray(a.search_log)) errors.push(`${tag}.search_log 배열 누락 (W-1)`);
    if (typeof a.seed !== "number") errors.push(`${tag}.seed 누락`);

    // character/prop transparent PNG 강제어 검증
    if (["character", "prop", "foreground"].includes(a.asset_type)) {
      if (
        !a.description_render.toLowerCase().includes("isolated") &&
        !a.description_render.toLowerCase().includes("transparent")
      ) {
        errors.push(
          `${tag}.description_render에 transparent PNG 지시어 누락 (asset_type=${a.asset_type})`
        );
      }
    }
    if (a.asset_type === "background") {
      if (
        a.description_render.toLowerCase().includes("isolated") ||
        a.description_render.toLowerCase().includes("transparent")
      ) {
        errors.push(`${tag}.description_render에 transparent 지시어 금지 (background)`);
      }
    }
  }
  return errors;
}

// ──────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────

const items = $input.all();
if (!items || items.length === 0) throw new Error("[Node 4] 입력 아이템 없음");

const node1 = $("Load Files").first().json;
const VIDEO_ID = node1.video_id;
const PROJECT_ROOT = node1.project_root;
if (!VIDEO_ID) throw new Error("[Node 4] video_id 누락");
if (!PROJECT_ROOT) throw new Error("[Node 4] project_root 누락");

const promptsDir = path.join(PROJECT_ROOT, "asset_prompts");
fs.mkdirSync(promptsDir, { recursive: true });

const allItems = [];
for (const item of items) {
  const j = item.json || {};
  if (!j.chapter_id || !j.plan_path) throw new Error("[Node 4] chapter_id/plan_path 누락");

  const catalogPath =
    j.catalog_path ||
    path.resolve(__dirname, "..", "..", "shared_assets", "references_catalog.json");
  if (!fs.existsSync(catalogPath)) throw new Error(`[Node 4] catalog 누락: ${catalogPath}`);
  if (!fs.existsSync(j.plan_path)) throw new Error(`[Node 4] plan 누락: ${j.plan_path}`);

  // 과제 11: hnswlib 인덱스 파일 (Node 9.5와 동일 위치)
  const indexPath =
    j.index_path || path.resolve(__dirname, "..", "..", "shared_assets", "references_catalog.idx");

  const promptsCachePath = path.join(promptsDir, `${j.chapter_id}_prompts.json`);
  if (fs.existsSync(promptsCachePath)) {
    const cached = JSON.parse(fs.readFileSync(promptsCachePath, "utf-8"));
    for (const a of cached) allItems.push({ json: a });
    continue;
  }

  const plan = JSON.parse(fs.readFileSync(j.plan_path, "utf-8"));
  const catalog = JSON.parse(fs.readFileSync(catalogPath, "utf-8"));

  const prompt = buildPrompt(plan, catalog);
  const geminiOutput = callGeminiCli(prompt);
  const enriched = postProcessAssets(geminiOutput, catalog, VIDEO_ID, { indexPath });

  const errors = validateAssets(enriched);
  if (errors.length > 0) {
    throw new Error(`[Node 4][${j.chapter_id}] 검증 실패:\n  - ${errors.join("\n  - ")}`);
  }

  fs.writeFileSync(promptsCachePath, JSON.stringify(enriched, null, 2), "utf-8");
  for (const a of enriched) allItems.push({ json: a });
}

return allItems;
