/**
 * Node 9.5 + embedding_search 단위 테스트 — Phase F 과제 10/11.
 *
 * 검증:
 *   1. acquireLock / releaseLock — atomic 보호 + stale recovery
 *   2. generateAssetId — SHA1 12자 결정론
 *   3. validateEntry — 필수 필드 검증
 *   4. upsertCatalog — auto_generated_assets 등재 + last_updated 갱신
 *   5. processItem — 통합 흐름 (registered / skipped / warning)
 *   6. embedding_search.searchAutoGenerated — 태그 3개 매칭 / 임베딩 폴백 / 임계값
 *
 * 실행: node n8n_workflow/nodes/node9_5_asset_archiver.test.js
 */

const fs = require("fs");
const path = require("path");
const os = require("os");

const archiver = require("./node9_5_asset_archiver.js");
const search = require("./embedding_search.js");

let pass = 0;
let fail = 0;

function eq(name, actual, expected) {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  if (ok) {
    pass++;
    console.log(`  ✔ ${name}`);
  } else {
    fail++;
    console.log(
      `  ✖ ${name}\n    expected: ${JSON.stringify(expected)}\n    actual:   ${JSON.stringify(actual)}`
    );
  }
}

function truthy(name, v) {
  if (v) {
    pass++;
    console.log(`  ✔ ${name}`);
  } else {
    fail++;
    console.log(`  ✖ ${name} (falsy)`);
  }
}

function approx(name, actual, expected, tol = 1e-6) {
  if (Math.abs(actual - expected) < tol) {
    pass++;
    console.log(`  ✔ ${name}`);
  } else {
    fail++;
    console.log(`  ✖ ${name}\n    expected: ${expected}\n    actual:   ${actual}`);
  }
}

// ──────────────────────────────────────────────
// 1. File Lock
// ──────────────────────────────────────────────

console.log("\n[1] File Lock (acquireLock / releaseLock)");

const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "node9_5_test_"));
const lockPath = path.join(tmpRoot, "test.lock");

eq("최초 획득 성공", archiver.acquireLock(lockPath), true);
truthy("락 파일 존재", fs.existsSync(lockPath));
eq("재획득 거부 (이미 점유)", archiver.acquireLock(lockPath), false);
archiver.releaseLock(lockPath);
truthy("해제 후 락 파일 부재", !fs.existsSync(lockPath));
eq(
  "재해제 ENOENT 무시",
  (() => {
    archiver.releaseLock(lockPath);
    return true;
  })(),
  true
);

// stale 복구
fs.writeFileSync(lockPath, "stale");
fs.utimesSync(lockPath, new Date(Date.now() - 60_000), new Date(Date.now() - 60_000));
eq("stale 락 강제 해제 후 재획득", archiver.acquireLock(lockPath), true);
archiver.releaseLock(lockPath);

// withLock 예외 시 자동 해제
let threw = false;
try {
  archiver.withLock(lockPath, () => {
    throw new Error("내부 오류");
  });
} catch (e) {
  threw = true;
}
truthy("withLock: 콜백 예외 전파", threw);
truthy("withLock: 예외 시에도 락 해제", !fs.existsSync(lockPath));

// ──────────────────────────────────────────────
// 2. generateAssetId
// ──────────────────────────────────────────────

console.log("\n[2] generateAssetId (SHA1 12자)");

const id1 = archiver.generateAssetId(
  "project/asset/chapter_01/scene_03/x.webp",
  "2026-04-30T00:00:00Z"
);
const id2 = archiver.generateAssetId(
  "project/asset/chapter_01/scene_03/x.webp",
  "2026-04-30T00:00:00Z"
);
eq("결정론 (동일 입력 → 동일 ID)", id1, id2);
truthy("auto_ 접두사", id1.startsWith("auto_"));
eq("hash 길이 12", id1.length, "auto_".length + 12);

const id3 = archiver.generateAssetId(
  "project/asset/chapter_01/scene_03/y.webp",
  "2026-04-30T00:00:00Z"
);
truthy("입력 다르면 ID 다름", id1 !== id3);

// ──────────────────────────────────────────────
// 3. validateEntry
// ──────────────────────────────────────────────

console.log("\n[3] validateEntry");

const validEntry = {
  asset_id: "auto_abc123",
  display_name: "테스트",
  description_search: "test phrase",
  description_render: "test full prompt",
  tags: ["test"],
  file_path: "assets/static/auto_generated/auto_abc123.webp",
  created_at: "2026-04-30T00:00:00Z",
  usage_count: 0,
  source_video_id: "vid_001",
  seed: 12345,
  lora_signature: "noir_webtoon_style@0.65",
  style_anchor_version: "1.0.0",
};
let ok = true;
try {
  archiver.validateEntry(validEntry);
} catch (e) {
  ok = false;
}
truthy("정상 entry 통과", ok);

let caught = false;
try {
  archiver.validateEntry({ ...validEntry, tags: undefined });
} catch (_) {
  caught = true;
}
truthy("tags 누락 시 throw", caught);

caught = false;
try {
  archiver.validateEntry({ ...validEntry, tags: "not-array" });
} catch (_) {
  caught = true;
}
truthy("tags 배열 아님 시 throw", caught);

// ──────────────────────────────────────────────
// 4. upsertCatalog
// ──────────────────────────────────────────────

console.log("\n[4] upsertCatalog");

const catalogPath = path.join(tmpRoot, "references_catalog.json");
fs.writeFileSync(
  catalogPath,
  JSON.stringify({ $schema_version: "2.0.0", auto_generated_assets: {} }, null, 2)
);

const upserted = archiver.upsertCatalog(catalogPath, validEntry);
truthy("auto_generated_assets에 등재", !!upserted.auto_generated_assets["auto_abc123"]);
truthy("last_updated 갱신", typeof upserted.last_updated === "string");

// 동일 ID 재호출 → 덮어쓰기 (upsert)
archiver.upsertCatalog(catalogPath, { ...validEntry, usage_count: 99 });
const reread = JSON.parse(fs.readFileSync(catalogPath, "utf-8"));
eq("upsert 갱신", reread.auto_generated_assets["auto_abc123"].usage_count, 99);

// ──────────────────────────────────────────────
// 5. processItem 통합 흐름
// ──────────────────────────────────────────────

console.log("\n[5] processItem 통합 흐름");

// 합성 레포 + project 구조
const repoRoot = fs.mkdtempSync(path.join(os.tmpdir(), "node9_5_repo_"));
const projectRoot = path.join(repoRoot, "project");
fs.mkdirSync(path.join(projectRoot, "asset", "chapter_01", "scene_03"), { recursive: true });
fs.mkdirSync(path.join(repoRoot, "shared_assets"), { recursive: true });
fs.mkdirSync(path.join(repoRoot, "assets", "static", "auto_generated"), { recursive: true });

const sourceFile = path.join(
  projectRoot,
  "asset",
  "chapter_01",
  "scene_03",
  "scene_03_prop_01.webp"
);
fs.writeFileSync(sourceFile, "fake-webp-bytes");

fs.writeFileSync(
  path.join(repoRoot, "shared_assets", "references_catalog.json"),
  JSON.stringify({ $schema_version: "2.0.0", auto_generated_assets: {} }, null, 2)
);

// generate_asset:false → skipped (no-op 통과)
let res = archiver.processItem({
  item: {
    chapter_id: "chapter_01",
    scene_id: "scene_03",
    scene_asset_id: "prop_01",
    asset_type: "prop",
    description_search: "skipped item",
    description_render: "skipped",
    tags: ["x"],
    generate_asset: false,
    output_path: "asset/chapter_01/scene_03/scene_03_prop_01.webp",
    seed: 1,
    lora_signature: "noir_webtoon_style@0.65",
  },
  projectRoot,
  repoRoot,
  videoId: "vid_001",
  styleAnchorVersion: "1.0.0",
  embedFn: () => [new Array(384).fill(0.1)],
});
eq("generate_asset:false → skipped", res.archive_status, "skipped");

// generate_asset:true + 정상 경로 → registered
res = archiver.processItem({
  item: {
    chapter_id: "chapter_01",
    scene_id: "scene_03",
    scene_asset_id: "prop_01",
    asset_type: "prop",
    description_search: "vintage briefcase leather",
    description_render: "vintage briefcase, leather, transparent background, noir webtoon style",
    tags: ["briefcase", "leather", "vintage"],
    generate_asset: true,
    output_path: "asset/chapter_01/scene_03/scene_03_prop_01.webp",
    seed: 12345,
    lora_signature: "noir_webtoon_style@0.65",
  },
  projectRoot,
  repoRoot,
  videoId: "vid_001",
  styleAnchorVersion: "1.0.0",
  embedFn: () => [new Array(384).fill(0.1)],
});
eq("generate_asset:true → registered", res.archive_status, "registered");
truthy("archived_asset_id 부여", !!res.archived_asset_id);
truthy("archived_path 부여", !!res.archived_path);
truthy(
  "사본 파일 존재 (assets/static/auto_generated/)",
  fs.existsSync(path.join(repoRoot, res.archived_path))
);

const catReread = JSON.parse(
  fs.readFileSync(path.join(repoRoot, "shared_assets", "references_catalog.json"), "utf-8")
);
truthy("카탈로그에 신규 항목 등재", !!catReread.auto_generated_assets[res.archived_asset_id]);
eq(
  "source_video_id 기록",
  catReread.auto_generated_assets[res.archived_asset_id].source_video_id,
  "vid_001"
);
eq("usage_count 0 시작", catReread.auto_generated_assets[res.archived_asset_id].usage_count, 0);

// 원본 파일 누락 → warning
res = archiver.processItem({
  item: {
    chapter_id: "chapter_01",
    scene_id: "scene_99",
    scene_asset_id: "prop_99",
    asset_type: "prop",
    description_search: "ghost",
    description_render: "ghost",
    tags: [],
    generate_asset: true,
    output_path: "asset/chapter_01/scene_99/missing.webp",
    seed: 1,
    lora_signature: "noir_webtoon_style@0.65",
  },
  projectRoot,
  repoRoot,
  videoId: "vid_001",
  styleAnchorVersion: "1.0.0",
  embedFn: () => [new Array(384).fill(0.1)],
});
eq("원본 누락 → warning", res.archive_status, "warning");
truthy("archive_warning 메시지", String(res.archive_warning).includes("원본 파일 부재"));

// ──────────────────────────────────────────────
// 6. embedding_search.searchAutoGenerated
// ──────────────────────────────────────────────

console.log("\n[6] searchAutoGenerated (태그 폴백 + 임베딩 임계값)");

const sampleCatalog = {
  auto_generated_assets: {
    auto_aaa: {
      asset_id: "auto_aaa",
      description_search: "vintage briefcase leather brown",
      tags: ["briefcase", "leather", "vintage", "brown"],
    },
    auto_bbb: {
      asset_id: "auto_bbb",
      description_search: "modern laptop silver thin",
      tags: ["laptop", "modern", "silver"],
    },
  },
};

// 태그 3개 일치 → 임베딩 호출 없이 즉시 매칭
let called = 0;
let r = search.searchAutoGenerated({
  catalog: sampleCatalog,
  indexPath: path.join(tmpRoot, "no.idx"),
  query: { description_search: "anything", tags: ["briefcase", "leather", "vintage"] },
  embedFn: () => {
    called++;
    return [new Array(384).fill(0)];
  },
});
truthy("태그 3개 일치 → hit", !!r.hit);
eq("태그 매칭 source", r.hit && r.hit.source, "tag_match");
eq("태그 매칭 시 임베딩 호출 0회", called, 0);

// 임베딩 폴백 — 동일 벡터 → cosine 1.0 ≥ 0.85
r = search.searchAutoGenerated({
  catalog: sampleCatalog,
  indexPath: path.join(tmpRoot, "no.idx"),
  query: { description_search: "vintage briefcase leather brown", tags: [] },
  embedFn: (texts) =>
    texts.map(() => {
      const v = new Array(384).fill(0);
      v[0] = 1;
      return v;
    }),
});
truthy("동일 벡터 → 폴백 코사인 매칭", !!r.hit);
truthy(
  "source가 hnswlib 또는 fallback_cosine",
  ["hnswlib", "fallback_cosine"].includes(r.hit && r.hit.source)
);

// 임베딩 미달 — query는 차원 0, candidates는 차원 10/20 → 직교 (cosine 0)
let embedCall = 0;
r = search.searchAutoGenerated({
  catalog: sampleCatalog,
  indexPath: path.join(tmpRoot, "no.idx"),
  query: { description_search: "unrelated", tags: [] },
  embedFn: (texts) => {
    const isQuery = embedCall === 0;
    embedCall++;
    return texts.map((t, i) => {
      const v = new Array(384).fill(0);
      v[isQuery ? 0 : 10 + i] = 1;
      return v;
    });
  },
});
eq("임계값 미달 → hit:null", r.hit, null);

// 빈 카탈로그
r = search.searchAutoGenerated({
  catalog: { auto_generated_assets: {} },
  indexPath: path.join(tmpRoot, "no.idx"),
  query: { description_search: "x", tags: [] },
  embedFn: () => [new Array(384).fill(0)],
});
eq("빈 카탈로그 → hit:null", r.hit, null);
eq("빈 카탈로그 reason", r.log && r.log.reason, "no_auto_generated_assets");

// cosine
approx("cosine 동일 벡터 = 1.0", search.cosine([1, 0, 0], [1, 0, 0]), 1.0);
approx("cosine 직교 벡터 = 0", search.cosine([1, 0, 0], [0, 1, 0]), 0);

// tagMatchScore
eq("tagMatchScore 3개 일치", search.tagMatchScore(["a", "b", "c"], ["a", "b", "c", "d"]), 3);
eq("tagMatchScore 0개", search.tagMatchScore(["x"], ["a", "b"]), 0);
eq("tagMatchScore 대소문자 무시", search.tagMatchScore(["LEATHER"], ["leather"]), 1);

// ──────────────────────────────────────────────
// 7. addToIndex sidecar (hnswlib 미설치 폴백 모드)
// ──────────────────────────────────────────────

console.log("\n[7] addToIndex sidecar 라벨 매핑");

const idxPath = path.join(tmpRoot, "test.idx");
const a1 = search.addToIndex(idxPath, "auto_xxx", new Array(384).fill(0.1));
truthy("addToIndex ok", a1.ok);
truthy("라벨 sidecar 파일 생성", fs.existsSync(`${idxPath}.labels.json`));

const labels = search.loadLabels(idxPath);
truthy("auto_xxx 라벨 등록", "auto_xxx" in labels.labels);
eq("next_label 증가", labels.next_label, 1);

const a2 = search.addToIndex(idxPath, "auto_xxx", new Array(384).fill(0.1));
truthy(
  "동일 ID 재호출 → already_indexed",
  a2.note === "already_indexed" || a2.label === labels.labels["auto_xxx"]
);

console.log(`\n결과: ${pass} pass / ${fail} fail`);
process.exit(fail === 0 ? 0 : 1);
