/**
 * Node 9.5 — Asset Archiver (n8n Code Node, JavaScript)
 *
 * 목적: Node 4가 generate_asset:true로 마킹한 신규 창작 에셋을
 *      references_catalog.json[auto_generated_assets]에 자동 등재.
 *      자가 발전 라이브러리 폐쇄 루프(Phase F) 핵심.
 *
 * 과제 10 (Phase F) 핵심 동작:
 *   (1) 대상 필터링 — generate_asset:true만 처리, 그 외 통과
 *   (2) 사본 저장 — assets/static/auto_generated/auto_<sha1_12>.webp
 *       (원본은 project/asset/<chapter>/<scene>/ 그대로 유지)
 *   (3) File Lock — references_catalog.json.lock atomic 생성/제거
 *       n8n 환경 호환 위해 proper-lockfile 미사용 → 빌트인 fs.openSync(..., "wx") 기반
 *   (4) 카탈로그 upsert — auto_generated_assets에 메타 등재
 *   (5) hnswlib 인덱스 갱신 — references_catalog.idx에 description_search 임베딩 addPoint
 *       (실패 시 경고만 — 카탈로그는 유지, 다음 영상에서 재인덱스 가능)
 *   (6) 비대화 자동 삭제 금지 — usage_count==0 + 6개월 미사용은 운영자 수동 청소
 *
 * 입력 (n8n items[].json — Node 9 출력 + Node 4 메타 통과):
 *   {
 *     chapter_id, scene_id, scene_asset_id, asset_type,
 *     description_search, description_render, tags,
 *     generate_asset, lora_signature, seed, source_video_id?,
 *     output_path: "project/asset/<chapter>/<scene>/<scene_asset_id>.webp"
 *   }
 *
 * 워크플로우 전역 (Node 1):
 *   - $('Load Files').first().json.video_id
 *   - $('Load Files').first().json.project_root
 *   - $('Load Files').first().json.shared_assets_root  (옵션)
 *
 * 출력 (각 입력 1:1 — Node 10이 Node 9 산출 그대로 받도록 통과):
 *   { ...item, archive_status: "registered" | "skipped" | "warning",
 *     archived_asset_id?, archived_path?, archive_warning? }
 *
 * 환경: Node.js 빌트인만 (fs / path / crypto). 외부 npm 모듈 불필요.
 *      hnswlib-node는 옵셔널 require — 미설치 시 카탈로그만 갱신하고 경고.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// ──────────────────────────────────────────────
// 상수
// ──────────────────────────────────────────────

const AUTO_GEN_DIR_REL = "assets/static/auto_generated";
const CATALOG_REL = "shared_assets/references_catalog.json";
const INDEX_REL = "shared_assets/references_catalog.idx";
const LOCK_REL = "shared_assets/references_catalog.json.lock";
const STYLE_ANCHOR_VERSION_DEFAULT = "1.0.0";

const LOCK_RETRY_MAX = 5;
const LOCK_RETRY_BASE_MS = 50;
const LOCK_STALE_MS = 30_000; // 30초 — n8n 단일 챕터 처리 상한 충분

// ──────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────

function sha1Hex(s) {
  return crypto.createHash("sha1").update(s).digest("hex");
}

function nowIso() {
  return new Date().toISOString();
}

function readJsonSafe(p, label) {
  if (!fs.existsSync(p)) throw new Error(`[Node 9.5] ${label} 누락: ${p}`);
  try {
    return JSON.parse(fs.readFileSync(p, "utf-8"));
  } catch (e) {
    throw new Error(`[Node 9.5] ${label} 파싱 실패 (${p}): ${e.message}`);
  }
}

function atomicWriteJson(p, obj) {
  const tmp = `${p}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, JSON.stringify(obj, null, 2), "utf-8");
  fs.renameSync(tmp, p);
}

function sleepSync(ms) {
  const end = Date.now() + ms;
  while (Date.now() < end) {
    // busy wait — n8n Code Node에서 await 없이 동기 실행 보장
  }
}

// ──────────────────────────────────────────────
// File Lock — atomic create/release with stale recovery
// (W-7: proper-lockfile 미사용, 빌트인 fs로 동등 보호)
// ──────────────────────────────────────────────

function acquireLock(lockPath) {
  for (let attempt = 0; attempt < LOCK_RETRY_MAX; attempt++) {
    try {
      const fd = fs.openSync(lockPath, "wx");
      fs.writeSync(fd, JSON.stringify({ pid: process.pid, ts: Date.now() }));
      fs.closeSync(fd);
      return true;
    } catch (e) {
      if (e.code !== "EEXIST") throw e;

      // stale lock 검사 — 오래된 락은 강제 해제
      try {
        const stat = fs.statSync(lockPath);
        if (Date.now() - stat.mtimeMs > LOCK_STALE_MS) {
          fs.unlinkSync(lockPath);
          continue;
        }
      } catch (_) {
        // 다른 프로세스가 방금 해제 — 다시 시도
      }
      sleepSync(LOCK_RETRY_BASE_MS * (attempt + 1));
    }
  }
  return false;
}

function releaseLock(lockPath) {
  try {
    fs.unlinkSync(lockPath);
  } catch (e) {
    if (e.code !== "ENOENT") throw e;
  }
}

function withLock(lockPath, fn) {
  if (!acquireLock(lockPath)) {
    throw new Error(`[Node 9.5] File Lock 획득 실패 (${LOCK_RETRY_MAX}회 재시도): ${lockPath}`);
  }
  try {
    return fn();
  } finally {
    releaseLock(lockPath);
  }
}

// ──────────────────────────────────────────────
// 사본 저장 — assets/static/auto_generated/auto_<hash>.webp
// 파일명 hash: SHA1(asset_id + created_at) 앞 12자
// ──────────────────────────────────────────────

function generateAssetId(sourcePath, createdAt) {
  // 결정론: scene_asset_id 키와 created_at 결합 (테스트 가능)
  const base = `${sourcePath}|${createdAt}`;
  return `auto_${sha1Hex(base).slice(0, 12)}`;
}

function copyToAutoGenerated(sourceAbsPath, destAbsPath) {
  fs.mkdirSync(path.dirname(destAbsPath), { recursive: true });
  // copyFileSync는 atomic하지 않지만, dest는 SHA1 hash 키라 충돌 시 동일 파일
  fs.copyFileSync(sourceAbsPath, destAbsPath);
}

// ──────────────────────────────────────────────
// 카탈로그 upsert (auto_generated_assets)
// ──────────────────────────────────────────────

function buildCatalogEntry({ assetId, item, fileRelPath, createdAt, videoId, styleAnchorVersion }) {
  return {
    asset_id: assetId,
    display_name: item.display_name || item.scene_asset_id || assetId,
    description_search: item.description_search,
    description_render: item.description_render,
    tags: Array.isArray(item.tags) ? item.tags : [],
    file_path: fileRelPath,
    created_at: createdAt,
    usage_count: 0,
    source_video_id: videoId,
    seed: typeof item.seed === "number" ? item.seed : null,
    lora_signature: item.lora_signature || "noir_webtoon_style@0.65",
    style_anchor_version: styleAnchorVersion,
  };
}

function validateEntry(entry) {
  const required = [
    "asset_id",
    "display_name",
    "file_path",
    "description_search",
    "description_render",
    "tags",
    "created_at",
    "usage_count",
    "source_video_id",
    "seed",
    "lora_signature",
    "style_anchor_version",
  ];
  const missing = required.filter(
    (k) => entry[k] === undefined || (entry[k] === null && k !== "seed")
  );
  if (missing.length > 0) {
    throw new Error(`[Node 9.5] 카탈로그 등재 필드 누락: ${missing.join(", ")}`);
  }
  if (!Array.isArray(entry.tags)) {
    throw new Error("[Node 9.5] tags는 배열이어야 함");
  }
}

function upsertCatalog(catalogPath, entry) {
  const catalog = readJsonSafe(catalogPath, "references_catalog.json");
  catalog.auto_generated_assets = catalog.auto_generated_assets || {};
  catalog.auto_generated_assets[entry.asset_id] = entry;
  catalog.last_updated = nowIso().slice(0, 10);
  atomicWriteJson(catalogPath, catalog);
  return catalog;
}

// ──────────────────────────────────────────────
// 공용 임베딩 검색 레이어 위임 (과제 11)
// ──────────────────────────────────────────────

const embeddingSearch = require("./embedding_search.js");
const embedTexts = embeddingSearch.embedTexts;

// ──────────────────────────────────────────────
// 단일 아이템 처리
// ──────────────────────────────────────────────

function processItem({
  item,
  projectRoot,
  repoRoot,
  videoId,
  styleAnchorVersion,
  embedFn = embedTexts,
}) {
  // (1) 대상 필터
  if (!item.generate_asset) {
    return { ...item, archive_status: "skipped", archive_reason: "generate_asset:false" };
  }

  // 캐릭터/소품/static_asset hit은 generate_asset:false라 자동 통과 — 추가 가드 불필요

  // 사본 경로 결정
  if (!item.output_path) {
    return {
      ...item,
      archive_status: "warning",
      archive_warning: "output_path 누락 — Node 9 정규화 미적용",
    };
  }
  const sourceAbsPath = path.isAbsolute(item.output_path)
    ? item.output_path
    : path.join(projectRoot, item.output_path);
  if (!fs.existsSync(sourceAbsPath)) {
    return {
      ...item,
      archive_status: "warning",
      archive_warning: `원본 파일 부재: ${sourceAbsPath}`,
    };
  }

  const createdAt = nowIso();
  const assetId = generateAssetId(item.output_path, createdAt);
  const fileRel = `${AUTO_GEN_DIR_REL}/${assetId}.webp`;
  const fileAbs = path.join(repoRoot, fileRel);

  try {
    copyToAutoGenerated(sourceAbsPath, fileAbs);
  } catch (e) {
    // 사본 실패 — 원본은 보존, 운영자 알림용 경고만 반환
    return {
      ...item,
      archive_status: "warning",
      archive_warning: `사본 저장 실패: ${e.message}`,
    };
  }

  // (3) File Lock — 카탈로그 갱신 보호
  const catalogPath = path.join(repoRoot, CATALOG_REL);
  const lockPath = path.join(repoRoot, LOCK_REL);
  const indexPath = path.join(repoRoot, INDEX_REL);

  const entry = buildCatalogEntry({
    assetId,
    item,
    fileRelPath: fileRel,
    createdAt,
    videoId: item.source_video_id || videoId,
    styleAnchorVersion,
  });
  validateEntry(entry);

  let updatedCatalog;
  try {
    updatedCatalog = withLock(lockPath, () => upsertCatalog(catalogPath, entry));
  } catch (e) {
    return {
      ...item,
      archive_status: "warning",
      archive_warning: `카탈로그 갱신 실패: ${e.message}`,
      archived_asset_id: assetId,
      archived_path: fileRel,
    };
  }

  // (5) hnswlib 인덱스 즉시 addPoint — 실패해도 카탈로그는 유지
  let indexResult = { ok: false, reason: "skipped" };
  try {
    const [vec] = embedFn([item.description_search]);
    indexResult = embeddingSearch.addToIndex(indexPath, assetId, vec, vec.length);
  } catch (e) {
    indexResult = { ok: false, reason: `embed_failed:${e.message}` };
  }

  return {
    ...item,
    archive_status: "registered",
    archived_asset_id: assetId,
    archived_path: fileRel,
    archive_index_status: indexResult.ok ? "ok" : `warning:${indexResult.reason}`,
  };
}

// ──────────────────────────────────────────────
// Main (n8n Code Node entry)
// ──────────────────────────────────────────────

if (typeof $input === "undefined") {
  module.exports = {
    processItem,
    generateAssetId,
    buildCatalogEntry,
    validateEntry,
    upsertCatalog,
    acquireLock,
    releaseLock,
    withLock,
    constants: {
      AUTO_GEN_DIR_REL,
      CATALOG_REL,
      INDEX_REL,
      LOCK_REL,
      LOCK_STALE_MS,
    },
  };
} else {
  const items = $input.all();
  if (!items || items.length === 0) return [];

  const node1 = $("Load Files").first().json;
  const PROJECT_ROOT = node1.project_root;
  if (!PROJECT_ROOT) throw new Error("[Node 9.5] project_root 누락");
  const VIDEO_ID = node1.video_id || "unknown_video";

  // repo_root: shared_assets/references_catalog.json의 기준 — Vivid_Workspace 루트
  const REPO_ROOT = node1.repo_root || path.resolve(__dirname, "..", "..");

  // 글로벌 화풍 앵커 버전 (변경 시 자가 발전 라이브러리 demote)
  let styleAnchorVersion = STYLE_ANCHOR_VERSION_DEFAULT;
  try {
    const cat = readJsonSafe(path.join(REPO_ROOT, CATALOG_REL), "references_catalog.json");
    if (cat.global_style_anchor && cat.global_style_anchor.version) {
      styleAnchorVersion = cat.global_style_anchor.version;
    }
  } catch (_) {
    // catalog 읽기 실패는 default version으로 fall through
  }

  const out = [];
  for (const it of items) {
    const result = processItem({
      item: it.json || {},
      projectRoot: PROJECT_ROOT,
      repoRoot: REPO_ROOT,
      videoId: VIDEO_ID,
      styleAnchorVersion,
    });
    out.push({ json: result });
  }
  return out;
}
